AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  TemplateBucket:
    Type: String
Resources:
  TopicSubscribeStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/sns/topic-rss-subscribe.yaml"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
  TopicWriteStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/sns/topic-rss-write.yaml"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
  TopicTranslateStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/sns/topic-rss-translate.yaml"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
  TopicCleanStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/sns/topic-rss-clean.yaml"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
  TopicDeleteStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/sns/topic-rss-delete.yaml"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain