AWSTemplateFormatVersion: "2010-09-09"
Resources:
  TopicStack:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: rss-write-topic
      FifoTopic: false
Outputs:
  Arn:
    Value: !GetAtt TopicStack.TopicArn
    Export:
      Name: !Sub "RssWriteTopicArn"