AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TemplateBucket:
    Type: String
    Description: "The S3 bucket where the templates are stored"
  LambdaRoleArn:
    Type: String
  RestApiId:
    Type: String
  VersionResourceArn:
    Type: String

Resources:
  LambdaRssCreateStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.amazonaws.com/application/api/rss-create.yaml"
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        OutPutTopicRssArn: !ImportValue RssSubscribeTopicArn
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain

  Resource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref VersionResourceArn
      PathPart: rss
      RestApiId: !Ref RestApiId

  PostMethod:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.amazonaws.com/application/api/api-gateway-method.yaml"
      Parameters:
        HttpMethod: "POST"
        RestApiId: !Ref RestApiId
        ResourceId: !Ref Resource
        LambdaArn: !GetAtt  LambdaRssCreateStack.Outputs.Arn
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain

  OptionsMethod:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.amazonaws.com/application/api/api-gateway-option-method.yaml"
      Parameters:
        RestApiId: !Ref RestApiId
        ResourceId: !Ref Resource
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain

Outputs:
  ResourceArn:
    Value: !Ref Resource