AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TemplateBucket:
    Type: String
    Description: "The S3 bucket where the templates are stored"
  LambdaRoleArn:
    Type: String
  RestApiId:
    Type: String
  feedsResourceArn:
    Type: String

Resources:
  ResourceStack:
      Type: "AWS::CloudFormation::Stack"
      Properties:
        TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/application/api/api-gateway-resource-template-path.yaml"
        Parameters:
          RestApiId: !Ref RestApiId
          ParentId: !Ref feedsResourceArn
          PathPart: "{source}"
      DeletionPolicy: Delete
      UpdateReplacePolicy: Retain

  GetMethodStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/application/api/api-gateway-resource-template-method.yaml"
      Parameters:
        RestApiId: !Ref RestApiId
        ResourceId: !GetAtt ResourceStack.Outputs.ResourceArn
        HttpMethod: "GET"
        FunctionName: "RssFeedIdFunction"
        LambdaRoleArn: !Ref LambdaRoleArn
        CodeS3Bucket: !Ref TemplateBucket
        CodeS3Key: "binaries/rss/lambda/api/feed_id/function.zip"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain

  PathMethodStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/application/api/api-gateway-resource-template-method.yaml"
      Parameters:
        RestApiId: !Ref RestApiId
        ResourceId: !GetAtt ResourceStack.Outputs.ResourceArn
        HttpMethod: "PATCH"
        FunctionName: "RssPatchFunction"
        LambdaRoleArn: !Ref LambdaRoleArn
        CodeS3Bucket: !Ref TemplateBucket
        CodeS3Key: "binaries/rss/lambda/api/patch/function.zip"
        OutPutTopicRssArn: !ImportValue RssSubscribeTopicArn
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain

Outputs:
  ResourceArn:
    Value: !GetAtt ResourceStack.Outputs.ResourceArn