AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TemplateBucket:
    Type: String
    Description: "The S3 bucket where the templates are stored"
  LambdaRoleArn:
    Type: String
  RestApiId:
    Type: String
  VersionResourceArn:
    Type: String

Resources:
  LambdaRssCreateStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.amazonaws.com/application/api/rss-create.yaml"
      Parameters:
        LambdaRoleArn: !Ref LambdaRoleArn
        OutPutTopicRssArn: !ImportValue RssSubscribeTopicArn
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain

  ResourceStack:
      Type: "AWS::CloudFormation::Stack"
      Properties:
        TemplateURL: !Sub "https://${TemplateBucket}.s3.amazonaws.com/application/api/api-gateway-resource-template-path.yaml"
        Parameters:
          RestApiId: !Ref RestApiId
          ParentId: !Ref VersionResourceArn
          PathPart: rss
      DeletionPolicy: Delete
      UpdateReplacePolicy: Retain

  PostMethod:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.amazonaws.com/application/api/api-gateway-method.yaml"
      Parameters:
        HttpMethod: "POST"
        RestApiId: !Ref RestApiId
        ResourceId: !GetAtt ResourceStack.Outputs.ResourceArn
        LambdaArn: !GetAtt  LambdaRssCreateStack.Outputs.Arn
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain

Outputs:
  ResourceArn:
    Value: !GetAtt ResourceStack.Outputs.ResourceArn