AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  FunctionName:
    Type: String
  LambdaRoleArn:
    Type: String
  CodeS3Bucket:
    Type: String
    Description: "The S3 bucket where the code is stored"
  CodeS3Key:
    Type: String
    Description: "The S3 key where the code is stored"
  OutPutTopicRssArn:
    Type: String
    Default: ""
Resources:
  FunctionStack:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Handler: bootstrap
      Role: !Ref LambdaRoleArn
      Timeout: 10
      PackageType: Zip
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
      LoggingConfig:
        LogGroup: !Ref LambdaLogGroup
      Environment:
        Variables:
          OUTPUT_TOPIC_RSS_ARN: !Ref OutPutTopicRssArn
  LambdaLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub "/aws/lambda/${FunctionName}"
      RetentionInDays: 1
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref FunctionStack
      Principal: "apigateway.amazonaws.com"
Outputs:
  Arn:
    Value: !GetAtt 'FunctionStack.Arn'
  Name:
    Value: !Ref 'FunctionStack'
