version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l0m5q1g1
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG  -f Dockerfile-node .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG public.ecr.aws/l0m5q1g1/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Tagging the Docker image as latest...
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG public.ecr.aws/l0m5q1g1/$IMAGE_REPO_NAME:latest
  post_build:
    commands:
      - echo Pushing the Docker image with tag $IMAGE_TAG...
      - docker push public.ecr.aws/l0m5q1g1/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Tagging the Docker image as latest...
      - docker push public.ecr.aws/l0m5q1g1/$IMAGE_REPO_NAME:latest

env:
  variables:
    IMAGE_REPO_NAME: "nybeyond/workday"
    IMAGE_TAG: "0.0.6"
