# Node.jsの公式イメージをベースとする
FROM node:18

# アプリケーションディレクトリを作成
WORKDIR /app

# package.json と package-lock.json をコピー
COPY package*.json ./

# 依存関係のインストール
RUN npm install

# 必要なソースコードのみをコピー
COPY src/ src/
COPY tsconfig.json .

# TypeScriptのコンパイル
RUN npm run build

EXPOSE 3000

# アプリケーションの起動
CMD ["node", "dist/app.js"]
