version: "3.8"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'workday.ap-northeast-1.elasticbeanstalk.com -> http://app:3000'
      STAGE: 'production'
    volumes:
      - https-portal-data:/var/lib/https-portal
    depends_on:
      - app

  app:
    image : public.ecr.aws/l0m5q1g1/nybeyond/workday:0.0.1
    environment:
      - DOMAIN
      - NODE_ENV=production
      - FREE_CLIENT_ID
      - FREE_CLIENT_SECRET
      - REDIS_URL
      - SLACK_TOKEN
      - COGNITO_DOMAIN
      - COGNITO_USER_POOL_URL
      - COGNITO_CLIENT_ID
      - COGNITO_CLIENT_SECRET
    depends_on:
      - redis

  redis:
    image: public.ecr.aws/l0m5q1g1/nybeyond/workday-redis:0.0.1
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  https-portal-data: