# ベースイメージを指定
# 本来は Docker Hub の 'redis/redis-stack-server:7.2.0-v4' イメージを使用するのが一般的です。
# しかし、Docker Hub の匿名ユーザーに対するイメージダウンロード制限（レートリミット）により問題が発生する可能性があるため、
# 同等のイメージを Amazon ECR に配置しています。これにより、レートリミットを回避し、安定したビルドプロセスを保証します。
# 参考: https://matsuand.github.io/docs.docker.jp.onthefly/docker-hub/download-rate-limit/
#FROM redis/redis-stack-server:7.2.0-v4
FROM public.ecr.aws/l0m5q1g1/nybeyond/redis/redis-stack-server-7.2.0-v4:latest

# ホストシステムからコンテナに設定ファイルをコピー
COPY redis.conf /redis-stack.conf
COPY users.acl /users.acl

# Redisデータ用のボリュームを指定（オプション）
VOLUME /data

# Redisサーバーを実行
CMD ["redis-stack-server", "redis-stack.conf"]
