AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Rss:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "Rss"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "sortKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "sortKey"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 7
        WriteCapacityUnits: 7
      StreamSpecification:
        StreamViewType: 'NEW_IMAGE'
      SSESpecification:
        SSEEnabled: false
      TableClass: 'STANDARD'
      GlobalSecondaryIndexes:
        - IndexName: "SortKeyIndex"
          KeySchema:
            - AttributeName: "sortKey"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 3
            WriteCapacityUnits: 3
Outputs:
  Arn:
    Value: !GetAtt 'Rss.Arn'
    Export:
      Name: "RssTableArn"
  StreamArn:
    Value: !GetAtt 'Rss.StreamArn'
    Export:
      Name: "RssStreamArn"