AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  TemplateBucket:
    Type: String
Resources:
  EventStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.amazonaws.com/application/event/template.yaml"
      Parameters:
        TemplateBucket: !Ref TemplateBucket
  APIStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.amazonaws.com/application/api/template.yaml"
      Parameters:
        TemplateBucket: !Ref TemplateBucket