AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  RssWriteFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: ./../cmd/rss/lambda/event/write
      Environment:
        Variables:
          AWS_REGION_CODE: "us-west-2"
          DYNAMODB_ENDPOINT: "http://172.16.123.1:8000" 
      Events:
        SNSWriteTopic:
          Type: 'SNS'
          Properties:
            Topic: !Ref RssWriteSNSTopic
  RssWriteSNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: "prod-rss-write-topic"