AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  TemplateBucket:
    Type: String
  TranslateApiUrl:
    Type: String
Resources:
  LambdaRssNotificationStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/application/event/rss-notification.yaml"
      Parameters:
        LambdaRoleArn: !ImportValue LambdaRoleArn
        DynamoDBStreamArn: !ImportValue RssStreamArn
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
  LambdaRssTriggerStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/application/event/rss-trigger.yaml"
      Parameters:
        LambdaRoleArn: !ImportValue LambdaRoleArn
        SchedulerRoleArn: !ImportValue SchedulerRoleArn
        OutPutTopicRssArn: !ImportValue RssSubscribeTopicArn
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
  LambdaRssSubscribeStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/application/event/rss-subscribe.yaml"
      Parameters:
        LambdaRoleArn: !ImportValue LambdaRoleArn
        TriggerTopicRssArn: !ImportValue RssSubscribeTopicArn
        OutPutTopicRssArn: !ImportValue RssCleanTopicArn
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
  LambdaRssCleanStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/application/event/rss-clean.yaml"
      Parameters:
        LambdaRoleArn: !ImportValue LambdaRoleArn
        TriggerTopicRssArn: !ImportValue RssCleanTopicArn
        OutPutTopicRssArn: !ImportValue RssTranslateTopicArn
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
  LambdaRssTranslateStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/application/event/rss-translate.yaml"
      Parameters:
        LambdaRoleArn: !ImportValue LambdaRoleArn
        TriggerTopicRssArn: !ImportValue RssTranslateTopicArn
        OutPutTopicRssArn: !ImportValue RssWriteTopicArn
        TranslateApiUrl: !Ref TranslateApiUrl
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
  LambdaRssWriteStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/application/event/rss-write.yaml"
      Parameters:
        LambdaRoleArn: !ImportValue LambdaRoleArn
        TriggerTopicRssArn: !ImportValue RssWriteTopicArn
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
  LambdaRssDeleteStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/application/event/rss-delete.yaml"
      Parameters:
        LambdaRoleArn: !ImportValue LambdaRoleArn
        TriggerTopicRssArn: !ImportValue RssDeleteTopicArn
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain