AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "workday-scheduler-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'scheduler.amazonaws.com'
            Action: 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: 'SchedulerInvokeLambda'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 
                  - 'lambda:InvokeFunction'
                Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*Trigger*"
Outputs:
  Arn:
    Value: !GetAtt 'SchedulerRole.Arn'
    Export:
      Name: "SchedulerRoleArn"