AWSTemplateFormatVersion: "2010-09-09"
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "workday-lambda-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: 'LambdaS3AccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 
                  - 's3:Get*'
                  - 's3:List*'
                  - 's3:Describe*'
                  - 's3-object-lambda:Get*'
                  - 's3-object-lambda:List*'
                Resource: '*'
        - PolicyName: 'LambdaDynamoDBAccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'dynamodb:PutItem'
                  - 'dynamodb:Query'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:BatchWriteItem'
                Resource: 
                  - !ImportValue RssTableArn
                  - !Sub
                    - "${TableArn}/index/*"
                    - TableArn: !ImportValue RssTableArn
        - PolicyName: 'LambdaCloudWatchLogsPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'
        - PolicyName: 'LambdaSNSPublishPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'sns:Publish'
                Resource: 
                  - !ImportValue RssWriteTopicArn
                  - !ImportValue RssSubscribeTopicArn
                  - !ImportValue RssTranslateTopicArn
                  - !ImportValue RssCleanTopicArn
                  - !ImportValue RssDeleteTopicArn
        - PolicyName: 'LambdaTranslatePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'translate:TranslateText'
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaDynamoDBExecutionRole
Outputs:
  Arn:
    Value: !GetAtt 'LambdaRole.Arn'
    Export:
      Name: "LambdaRoleArn"